version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_local
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  mongodb_compass:
    image: mongo-express:latest
    container_name: mongodb_compass_local
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mongodb_data:
